- name: Set Hostname
  hostname: name="{{ project_name }}-{{ env }}"

- name: Upgrade All Packages
  package: name=* state=latest
  register: upgrade_all_packages

- name: Install Repo EPEL
  package: name=epel-release state=installed

- name: Install pip
  package: name={{ item }} state=installed
  with_items:
    - python-devel
    - python-pip

- name: Update pip
  pip: name=pip state=latest

- name: Install Docker Engine
  package: name={{item}} state=latest
  with_items:
    - docker
    - docker-registry
  register: install_docker_engine

- name: Install Docker-py and Docker-Compose
  pip: name={{item}}
  with_items:
    - docker-compose
    - docker-py

- name: Systemd Enable Docker
  systemd:
    name: docker
    state: started
    enabled: True
  register: systemd_enable_docker
